---
# 保存docker的日志
- hosts: dt
  remote_user: root

  tasks:
  # #将镜像通过tar文件load出来  
  - name: start cc service
    shell: sudo bash {{work_dir}}/build/cc/create-network-congestion0.sh

  # - name: download log 
  #   shell: bash {{work_dir}}/build/download-log.sh test-1m-16